# Generated by Django 4.2.7 on 2023-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
