# Generated by Django 4.2.7 on 2024-01-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_options_product_bla_bla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bla_bla',
        ),
    ]
